### PR TITLE
replaced latex with pdfkit #1

### PR DESCRIPTION
**Pull request by mreinstein**

### CODE REVIEW

**Comment by mreinstein** [comment]
this also fixes #2

**Comment by brianbianco** [comment]
+1. I am now using @mreinstein 's branch.  Would you kindly review and merge?

**Comment by boneskull** [comment]
I've published @mreinstein 's fixes (and another fix by me) to the `@boneskull/invoicer` package.

cc @brianbianco

**Comment by mreinstein** [comment]
@substack in #1 you expressed interest in pdfkit as a potential way to avoid needing external binaries to use invoiver. Is this PR something you'd be open to merging?

**Comment by account-archived-270316** [comment]
+1 this saves a lot of trouble regarding the pre-installation on macOS.

**Comment by boneskull** [comment]
@substack If you're interested, I'd be willing to help maintain this project.  I'd like to merge [the changes from my fork](https://github.com/substack/invoicer/compare/master...boneskull:master) in.

**Pull request closed without merging**
